CREATE DATABASE reportdb;
USE reportdb;

CREATE TABLE users(
user_id INT AUTO_INCREMENT PRIMARY KEY 
email VARCHAR(255) NOT NULL UNIQUE,
username VARCHAR(10) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role ENUM('user','admin') DEFAULT 'user' NOT NULL,
created_at TIMESTAMP default CURRENT_TIMESTAMP
);